#!perl
#
#@Pinned_Dodecahedron.pl
#
#---------------------------------
#A Script By Allan Kiipli (c) 2012
#---------------------------------
#
#Creates pinned dodecahedron on new layer.
#

$currentscene = lxq("query sceneservice scene.index ? current");

lxout("currentscene $currentscene");

$mainayer = lxq("query layerservice layers ? main");

lx("select.layer $mainayer");

$layerindex = lxq("query layerservice layer.index ? $mainayer");

lxout("layerindex $layerindex");

lx("select.drop item");

lx("select.symmetryState none");

$units = lxq("pref.value {units.system} ?");

lxout("units $units");

lx("pref.value units.system si");

#----------------------DispatchCoordinates Begin----------------------

lx("layer.new");

lx("item.name {pinned_dodecahedron}");

$main = lxq("query layerservice layers ? main");
$layerindex = lxq("query layerservice layer.index ? $main");
lx("tool.set prim.makeVertex on 0");
lx("tool.setAttr prim.makeVertex cenX 0.30901700258255");
lx("tool.setAttr prim.makeVertex cenY 0.5");
lx("tool.setAttr prim.makeVertex cenZ 0");
lx("tool.doApply");
lx("tool.setAttr prim.makeVertex cenX -0.30901700258255");
lx("tool.setAttr prim.makeVertex cenY 0.5");
lx("tool.setAttr prim.makeVertex cenZ 0");
lx("tool.doApply");
lx("tool.setAttr prim.makeVertex cenX 0.30901700258255");
lx("tool.setAttr prim.makeVertex cenY -0.5");
lx("tool.setAttr prim.makeVertex cenZ 0");
lx("tool.doApply");
lx("tool.setAttr prim.makeVertex cenX -0.30901700258255");
lx("tool.setAttr prim.makeVertex cenY -0.5");
lx("tool.setAttr prim.makeVertex cenZ 0");
lx("tool.doApply");
lx("tool.setAttr prim.makeVertex cenX -0.5");
lx("tool.setAttr prim.makeVertex cenY 0");
lx("tool.setAttr prim.makeVertex cenZ 0.30901700258255");
lx("tool.doApply");
lx("tool.setAttr prim.makeVertex cenX -0.5");
lx("tool.setAttr prim.makeVertex cenY 0");
lx("tool.setAttr prim.makeVertex cenZ -0.30901700258255");
lx("tool.doApply");
lx("tool.setAttr prim.makeVertex cenX 0.5");
lx("tool.setAttr prim.makeVertex cenY 0");
lx("tool.setAttr prim.makeVertex cenZ 0.30901700258255");
lx("tool.doApply");
lx("tool.setAttr prim.makeVertex cenX 0.5");
lx("tool.setAttr prim.makeVertex cenY 0");
lx("tool.setAttr prim.makeVertex cenZ -0.30901700258255");
lx("tool.doApply");
lx("tool.setAttr prim.makeVertex cenX 0");
lx("tool.setAttr prim.makeVertex cenY 0.30901700258255");
lx("tool.setAttr prim.makeVertex cenZ -0.5");
lx("tool.doApply");
lx("tool.setAttr prim.makeVertex cenX 0");
lx("tool.setAttr prim.makeVertex cenY -0.30901700258255");
lx("tool.setAttr prim.makeVertex cenZ -0.5");
lx("tool.doApply");
lx("tool.setAttr prim.makeVertex cenX 0");
lx("tool.setAttr prim.makeVertex cenY 0.30901700258255");
lx("tool.setAttr prim.makeVertex cenZ 0.5");
lx("tool.doApply");
lx("tool.setAttr prim.makeVertex cenX 0");
lx("tool.setAttr prim.makeVertex cenY -0.30901700258255");
lx("tool.setAttr prim.makeVertex cenZ 0.5");
lx("tool.doApply");
lx("tool.setAttr prim.makeVertex cenX 0");
lx("tool.setAttr prim.makeVertex cenY -1.30901694297791");
lx("tool.setAttr prim.makeVertex cenZ -0.5");
lx("tool.doApply");
lx("tool.setAttr prim.makeVertex cenX -1.30901694297791");
lx("tool.setAttr prim.makeVertex cenY -0.5");
lx("tool.setAttr prim.makeVertex cenZ 0");
lx("tool.doApply");
lx("tool.setAttr prim.makeVertex cenX -0.80901700258255");
lx("tool.setAttr prim.makeVertex cenY -0.80901700258255");
lx("tool.setAttr prim.makeVertex cenZ -0.80901700258255");
lx("tool.doApply");
lx("tool.setAttr prim.makeVertex cenX -0.5");
lx("tool.setAttr prim.makeVertex cenY 0");
lx("tool.setAttr prim.makeVertex cenZ -1.30901694297791");
lx("tool.doApply");
lx("tool.setAttr prim.makeVertex cenX 1.30901694297791");
lx("tool.setAttr prim.makeVertex cenY -0.5");
lx("tool.setAttr prim.makeVertex cenZ 0");
lx("tool.doApply");
lx("tool.setAttr prim.makeVertex cenX 0.80901700258255");
lx("tool.setAttr prim.makeVertex cenY -0.80901700258255");
lx("tool.setAttr prim.makeVertex cenZ -0.80901700258255");
lx("tool.doApply");
lx("tool.setAttr prim.makeVertex cenX 0.5");
lx("tool.setAttr prim.makeVertex cenY 0");
lx("tool.setAttr prim.makeVertex cenZ -1.30901694297791");
lx("tool.doApply");
lx("tool.setAttr prim.makeVertex cenX 0");
lx("tool.setAttr prim.makeVertex cenY 1.30901694297791");
lx("tool.setAttr prim.makeVertex cenZ -0.5");
lx("tool.doApply");
lx("tool.setAttr prim.makeVertex cenX -1.30901694297791");
lx("tool.setAttr prim.makeVertex cenY 0.5");
lx("tool.setAttr prim.makeVertex cenZ 0");
lx("tool.doApply");
lx("tool.setAttr prim.makeVertex cenX -0.80901700258255");
lx("tool.setAttr prim.makeVertex cenY 0.80901700258255");
lx("tool.setAttr prim.makeVertex cenZ -0.80901700258255");
lx("tool.doApply");
lx("tool.setAttr prim.makeVertex cenX 1.30901694297791");
lx("tool.setAttr prim.makeVertex cenY 0.5");
lx("tool.setAttr prim.makeVertex cenZ 0");
lx("tool.doApply");
lx("tool.setAttr prim.makeVertex cenX 0.80901700258255");
lx("tool.setAttr prim.makeVertex cenY 0.80901700258255");
lx("tool.setAttr prim.makeVertex cenZ -0.80901700258255");
lx("tool.doApply");
lx("tool.setAttr prim.makeVertex cenX 0");
lx("tool.setAttr prim.makeVertex cenY -1.30901694297791");
lx("tool.setAttr prim.makeVertex cenZ 0.5");
lx("tool.doApply");
lx("tool.setAttr prim.makeVertex cenX -0.80901700258255");
lx("tool.setAttr prim.makeVertex cenY -0.80901700258255");
lx("tool.setAttr prim.makeVertex cenZ 0.80901700258255");
lx("tool.doApply");
lx("tool.setAttr prim.makeVertex cenX -0.5");
lx("tool.setAttr prim.makeVertex cenY 0");
lx("tool.setAttr prim.makeVertex cenZ 1.30901694297791");
lx("tool.doApply");
lx("tool.setAttr prim.makeVertex cenX 0.80901700258255");
lx("tool.setAttr prim.makeVertex cenY -0.80901700258255");
lx("tool.setAttr prim.makeVertex cenZ 0.80901700258255");
lx("tool.doApply");
lx("tool.setAttr prim.makeVertex cenX 0.5");
lx("tool.setAttr prim.makeVertex cenY 0");
lx("tool.setAttr prim.makeVertex cenZ 1.30901694297791");
lx("tool.doApply");
lx("tool.setAttr prim.makeVertex cenX 0");
lx("tool.setAttr prim.makeVertex cenY 1.30901694297791");
lx("tool.setAttr prim.makeVertex cenZ 0.5");
lx("tool.doApply");
lx("tool.setAttr prim.makeVertex cenX -0.80901700258255");
lx("tool.setAttr prim.makeVertex cenY 0.80901700258255");
lx("tool.setAttr prim.makeVertex cenZ 0.80901700258255");
lx("tool.doApply");
lx("tool.setAttr prim.makeVertex cenX 0.80901700258255");
lx("tool.setAttr prim.makeVertex cenY 0.80901700258255");
lx("tool.setAttr prim.makeVertex cenZ 0.80901700258255");
lx("tool.doApply");
lx("tool.set prim.makeVertex off 0");
lx("select.drop vertex");
lx("select.element $layerindex vertex add 23");
lx("select.element $layerindex vertex add 19");
lx("select.element $layerindex vertex add 0");
lx("poly.make face");
lx("select.element $layerindex vertex add 23");
lx("select.element $layerindex vertex add 0");
lx("select.element $layerindex vertex add 22");
lx("poly.make face");
lx("select.element $layerindex vertex add 19");
lx("select.element $layerindex vertex add 29");
lx("select.element $layerindex vertex add 0");
lx("poly.make face");
lx("select.element $layerindex vertex add 31");
lx("select.element $layerindex vertex add 0");
lx("select.element $layerindex vertex add 29");
lx("poly.make face");
lx("select.element $layerindex vertex add 0");
lx("select.element $layerindex vertex add 31");
lx("select.element $layerindex vertex add 22");
lx("poly.make face");
lx("select.element $layerindex vertex add 21");
lx("select.element $layerindex vertex add 1");
lx("select.element $layerindex vertex add 19");
lx("poly.make face");
lx("select.element $layerindex vertex add 21");
lx("select.element $layerindex vertex add 20");
lx("select.element $layerindex vertex add 1");
lx("poly.make face");
lx("select.element $layerindex vertex add 19");
lx("select.element $layerindex vertex add 1");
lx("select.element $layerindex vertex add 29");
lx("poly.make face");
lx("select.element $layerindex vertex add 30");
lx("select.element $layerindex vertex add 29");
lx("select.element $layerindex vertex add 1");
lx("poly.make face");
lx("select.element $layerindex vertex add 1");
lx("select.element $layerindex vertex add 20");
lx("select.element $layerindex vertex add 30");
lx("poly.make face");
lx("select.element $layerindex vertex add 17");
lx("select.element $layerindex vertex add 2");
lx("select.element $layerindex vertex add 12");
lx("poly.make face");
lx("select.element $layerindex vertex add 17");
lx("select.element $layerindex vertex add 16");
lx("select.element $layerindex vertex add 2");
lx("poly.make face");
lx("select.element $layerindex vertex add 12");
lx("select.element $layerindex vertex add 2");
lx("select.element $layerindex vertex add 24");
lx("poly.make face");
lx("select.element $layerindex vertex add 27");
lx("select.element $layerindex vertex add 24");
lx("select.element $layerindex vertex add 2");
lx("poly.make face");
lx("select.element $layerindex vertex add 2");
lx("select.element $layerindex vertex add 16");
lx("select.element $layerindex vertex add 27");
lx("poly.make face");
lx("select.element $layerindex vertex add 14");
lx("select.element $layerindex vertex add 12");
lx("select.element $layerindex vertex add 3");
lx("poly.make face");
lx("select.element $layerindex vertex add 14");
lx("select.element $layerindex vertex add 3");
lx("select.element $layerindex vertex add 13");
lx("poly.make face");
lx("select.element $layerindex vertex add 12");
lx("select.element $layerindex vertex add 24");
lx("select.element $layerindex vertex add 3");
lx("poly.make face");
lx("select.element $layerindex vertex add 25");
lx("select.element $layerindex vertex add 3");
lx("select.element $layerindex vertex add 24");
lx("poly.make face");
lx("select.element $layerindex vertex add 3");
lx("select.element $layerindex vertex add 25");
lx("select.element $layerindex vertex add 13");
lx("poly.make face");
lx("select.element $layerindex vertex add 30");
lx("select.element $layerindex vertex add 20");
lx("select.element $layerindex vertex add 4");
lx("poly.make face");
lx("select.element $layerindex vertex add 30");
lx("select.element $layerindex vertex add 4");
lx("select.element $layerindex vertex add 26");
lx("poly.make face");
lx("select.element $layerindex vertex add 20");
lx("select.element $layerindex vertex add 13");
lx("select.element $layerindex vertex add 4");
lx("poly.make face");
lx("select.element $layerindex vertex add 25");
lx("select.element $layerindex vertex add 4");
lx("select.element $layerindex vertex add 13");
lx("poly.make face");
lx("select.element $layerindex vertex add 4");
lx("select.element $layerindex vertex add 25");
lx("select.element $layerindex vertex add 26");
lx("poly.make face");
lx("select.element $layerindex vertex add 21");
lx("select.element $layerindex vertex add 5");
lx("select.element $layerindex vertex add 20");
lx("poly.make face");
lx("select.element $layerindex vertex add 21");
lx("select.element $layerindex vertex add 15");
lx("select.element $layerindex vertex add 5");
lx("poly.make face");
lx("select.element $layerindex vertex add 20");
lx("select.element $layerindex vertex add 5");
lx("select.element $layerindex vertex add 13");
lx("poly.make face");
lx("select.element $layerindex vertex add 14");
lx("select.element $layerindex vertex add 13");
lx("select.element $layerindex vertex add 5");
lx("poly.make face");
lx("select.element $layerindex vertex add 5");
lx("select.element $layerindex vertex add 15");
lx("select.element $layerindex vertex add 14");
lx("poly.make face");
lx("select.element $layerindex vertex add 31");
lx("select.element $layerindex vertex add 6");
lx("select.element $layerindex vertex add 22");
lx("poly.make face");
lx("select.element $layerindex vertex add 31");
lx("select.element $layerindex vertex add 28");
lx("select.element $layerindex vertex add 6");
lx("poly.make face");
lx("select.element $layerindex vertex add 22");
lx("select.element $layerindex vertex add 6");
lx("select.element $layerindex vertex add 16");
lx("poly.make face");
lx("select.element $layerindex vertex add 27");
lx("select.element $layerindex vertex add 16");
lx("select.element $layerindex vertex add 6");
lx("poly.make face");
lx("select.element $layerindex vertex add 6");
lx("select.element $layerindex vertex add 28");
lx("select.element $layerindex vertex add 27");
lx("poly.make face");
lx("select.element $layerindex vertex add 23");
lx("select.element $layerindex vertex add 22");
lx("select.element $layerindex vertex add 7");
lx("poly.make face");
lx("select.element $layerindex vertex add 23");
lx("select.element $layerindex vertex add 7");
lx("select.element $layerindex vertex add 18");
lx("poly.make face");
lx("select.element $layerindex vertex add 22");
lx("select.element $layerindex vertex add 16");
lx("select.element $layerindex vertex add 7");
lx("poly.make face");
lx("select.element $layerindex vertex add 17");
lx("select.element $layerindex vertex add 7");
lx("select.element $layerindex vertex add 16");
lx("poly.make face");
lx("select.element $layerindex vertex add 7");
lx("select.element $layerindex vertex add 17");
lx("select.element $layerindex vertex add 18");
lx("poly.make face");
lx("select.element $layerindex vertex add 23");
lx("select.element $layerindex vertex add 18");
lx("select.element $layerindex vertex add 8");
lx("poly.make face");
lx("select.element $layerindex vertex add 23");
lx("select.element $layerindex vertex add 8");
lx("select.element $layerindex vertex add 19");
lx("poly.make face");
lx("select.element $layerindex vertex add 18");
lx("select.element $layerindex vertex add 15");
lx("select.element $layerindex vertex add 8");
lx("poly.make face");
lx("select.element $layerindex vertex add 21");
lx("select.element $layerindex vertex add 8");
lx("select.element $layerindex vertex add 15");
lx("poly.make face");
lx("select.element $layerindex vertex add 8");
lx("select.element $layerindex vertex add 21");
lx("select.element $layerindex vertex add 19");
lx("poly.make face");
lx("select.element $layerindex vertex add 17");
lx("select.element $layerindex vertex add 9");
lx("select.element $layerindex vertex add 18");
lx("poly.make face");
lx("select.element $layerindex vertex add 17");
lx("select.element $layerindex vertex add 12");
lx("select.element $layerindex vertex add 9");
lx("poly.make face");
lx("select.element $layerindex vertex add 18");
lx("select.element $layerindex vertex add 9");
lx("select.element $layerindex vertex add 15");
lx("poly.make face");
lx("select.element $layerindex vertex add 14");
lx("select.element $layerindex vertex add 15");
lx("select.element $layerindex vertex add 9");
lx("poly.make face");
lx("select.element $layerindex vertex add 9");
lx("select.element $layerindex vertex add 12");
lx("select.element $layerindex vertex add 14");
lx("poly.make face");
lx("select.element $layerindex vertex add 31");
lx("select.element $layerindex vertex add 10");
lx("select.element $layerindex vertex add 28");
lx("poly.make face");
lx("select.element $layerindex vertex add 31");
lx("select.element $layerindex vertex add 29");
lx("select.element $layerindex vertex add 10");
lx("poly.make face");
lx("select.element $layerindex vertex add 28");
lx("select.element $layerindex vertex add 10");
lx("select.element $layerindex vertex add 26");
lx("poly.make face");
lx("select.element $layerindex vertex add 30");
lx("select.element $layerindex vertex add 26");
lx("select.element $layerindex vertex add 10");
lx("poly.make face");
lx("select.element $layerindex vertex add 10");
lx("select.element $layerindex vertex add 29");
lx("select.element $layerindex vertex add 30");
lx("poly.make face");
lx("select.element $layerindex vertex add 27");
lx("select.element $layerindex vertex add 28");
lx("select.element $layerindex vertex add 11");
lx("poly.make face");
lx("select.element $layerindex vertex add 27");
lx("select.element $layerindex vertex add 11");
lx("select.element $layerindex vertex add 24");
lx("poly.make face");
lx("select.element $layerindex vertex add 28");
lx("select.element $layerindex vertex add 26");
lx("select.element $layerindex vertex add 11");
lx("poly.make face");
lx("select.element $layerindex vertex add 25");
lx("select.element $layerindex vertex add 11");
lx("select.element $layerindex vertex add 26");
lx("poly.make face");
lx("select.element $layerindex vertex add 11");
lx("select.element $layerindex vertex add 25");
lx("select.element $layerindex vertex add 24");
lx("poly.make face");
lx("tool.set uv.create on");
lx("tool.attr uv.create proj barycentric");
lx("tool.setAttr uv.create cenX 0.0");
lx("tool.setAttr uv.create cenY 0.0");
lx("tool.setAttr uv.create cenZ 0.0");
lx("tool.setAttr uv.create sizX [5^.5*.5+.5]");
lx("tool.setAttr uv.create sizY [5^.5*.5+.5]");
lx("tool.setAttr uv.create sizZ [5^.5*.5+.5]");
lx("tool.setAttr uv.create seam 0.0");
lx("tool.setAttr uv.create axis 2");
lx("tool.doApply");
lx("tool.set uv.create off 0");
lx("uv.pack true false false auto 0.2 false");
lx("select.type edge");
lx("select.element $layerindex edge set 19 0 0");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 0 23 0");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 19 29 2");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 29 0 2");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 31 0 3");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 21 1 5");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 1 19 5");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 1 29 7");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 30 29 8");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 1 30 8");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 20 30 9");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 17 2 10");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 2 12 10");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 2 24 12");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 24 12 12");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 2 27 13");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 16 27 14");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 14 12 15");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 12 3 15");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 3 14 15");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 13 14 16");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 24 3 17");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 25 3 18");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 20 4 20");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 4 30 20");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 20 13 22");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 13 4 22");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 25 4 23");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 21 5 25");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 5 20 25");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 5 13 27");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 5 14 28");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 15 14 29");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 31 6 30");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 6 22 30");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 6 16 32");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 16 22 32");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 6 27 33");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 22 7 35");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 7 23 35");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 16 7 37");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 17 7 38");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 18 8 40");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 8 23 40");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 18 15 42");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 15 8 42");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 21 8 43");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 17 9 45");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 9 18 45");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 9 15 47");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 9 14 48");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 31 10 50");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 10 28 50");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 10 26 52");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 26 28 52");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 10 30 53");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 28 11 55");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 11 27 55");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 26 11 57");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 25 11 58");
lx("uv.sewMove select 1");
lx("uv.fit false");
lx("select.drop polygon");
lx("tool.set actr.auto on");
lx("tool.set TransformScale on");
lx("tool.reset");
lx("tool.viewType uv");
lx("tool.setAttr xfrm.transform SX .99");
lx("tool.setAttr xfrm.transform SY .99");
lx("tool.doApply");
lx("tool.set TransformScale off");
lx("tool.set TransformMove on");
lx("tool.reset");
lx("tool.viewType uv");
lx("tool.setAttr xfrm.transform U .005");
lx("tool.setAttr xfrm.transform V .005");
lx("tool.doApply");
lx("tool.viewType xyz");
lx("tool.set TransformMove off");
lx("tool.set actr.auto off");
lx("select.drop vertex");

lx("pref.value units.system $units");
