#!perl
#
#@Snubdodecahedron.pl
#
#---------------------------------
#A Script By Allan Kiipli (c) 2012
#---------------------------------
#
#Creates Snubdodecahedron on new layer.
#
#
#----------------------------------dmccooey.com----------------------------------

$phi = (1 + sqrt(5)) / 2;
$x = (($phi + sqrt($phi-5/27))/2)**(1/3) + (($phi - sqrt($phi-5/27))/2)**(1/3);

$C0  = $phi * sqrt(3 - ($x**2)) / 2;
$C1  = $x * $phi * sqrt(3 - ($x**2)) / 2;
$C2  = $phi * sqrt(($x - 1 - (1/$x)) * $phi) / 2;
$C3  = ($x**2) * $phi * sqrt(3 - ($x**2)) / 2;
$C4  = $x * $phi * sqrt(($x - 1 - (1/$x)) * $phi) / 2;
$C5  = $phi * sqrt(1 - $x + ($phi + 1) / $x) / 2;
$C6  = $phi * sqrt($x - $phi + 1) / 2;
$C7  = ($x**2) * $phi * sqrt(($x - 1 - (1/$x)) * $phi) / 2;
$C8  = $x * $phi * sqrt(1 - $x + ($phi + 1) / $x) / 2;
$C9  = sqrt(($x + 2) * $phi + 2) / 2;
$C10 = $x * sqrt($x * ($phi + 1) - $phi) / 2;
$C11 = sqrt(($x**2) * (2 * $phi + 1) - $phi) / 2;
$C12 = $phi * sqrt(($x**2) + $x) / 2;
$C13 = ($phi**2) * sqrt($x * ($x + $phi) + 1) / (2 * $x);
$C14 = $phi * sqrt($x * ($x + $phi) + 1) / 2;

#---------------------------------------------------------------------------------

$currentscene = lxq("query sceneservice scene.index ? current");

lxout("currentscene $currentscene");

$mainayer = lxq("query layerservice layers ? main");

lx("select.layer $mainayer");

$layerindex = lxq("query layerservice layer.index ? $mainayer");

lxout("layerindex $layerindex");

$units = lxq("pref.value {units.system} ?");

lx("pref.value units.system si");

lxout("units $units");

lx("select.drop item");

lx("select.symmetryState none");

#----------------------DispatchCoordinates Begin----------------------

lx("layer.new");

lx("item.name {snubdodecahedron}");

$main = lxq("query layerservice layers ? main");
$layerindex = lxq("query layerservice layer.index ? $main");
lx("tool.set prim.makeVertex on 0");
lx("tool.setAttr prim.makeVertex cenX -$C10");
lx("tool.setAttr prim.makeVertex cenY -$C5");
lx("tool.setAttr prim.makeVertex cenZ -$C9");
lx("tool.doApply");
lx("tool.setAttr prim.makeVertex cenX -$C5");
lx("tool.setAttr prim.makeVertex cenY -$C9");
lx("tool.setAttr prim.makeVertex cenZ -$C10");
lx("tool.doApply");
lx("tool.setAttr prim.makeVertex cenX -$C4");
lx("tool.setAttr prim.makeVertex cenY -$C3");
lx("tool.setAttr prim.makeVertex cenZ -$C13");
lx("tool.doApply");
lx("tool.setAttr prim.makeVertex cenX $C6");
lx("tool.setAttr prim.makeVertex cenY -$C7");
lx("tool.setAttr prim.makeVertex cenZ -$C11");
lx("tool.doApply");
lx("tool.setAttr prim.makeVertex cenX $C1");
lx("tool.setAttr prim.makeVertex cenY -$C2");
lx("tool.setAttr prim.makeVertex cenZ -$C14");
lx("tool.doApply");
lx("tool.setAttr prim.makeVertex cenX $C11");
lx("tool.setAttr prim.makeVertex cenY -$C6");
lx("tool.setAttr prim.makeVertex cenZ -$C7");
lx("tool.doApply");
lx("tool.setAttr prim.makeVertex cenX $C8");
lx("tool.setAttr prim.makeVertex cenY -$C0");
lx("tool.setAttr prim.makeVertex cenZ -$C12");
lx("tool.doApply");
lx("tool.setAttr prim.makeVertex cenX -$C11");
lx("tool.setAttr prim.makeVertex cenY $C6");
lx("tool.setAttr prim.makeVertex cenZ -$C7");
lx("tool.doApply");
lx("tool.setAttr prim.makeVertex cenX -$C0");
lx("tool.setAttr prim.makeVertex cenY $C12");
lx("tool.setAttr prim.makeVertex cenZ -$C8");
lx("tool.doApply");
lx("tool.setAttr prim.makeVertex cenX -$C6");
lx("tool.setAttr prim.makeVertex cenY $C7");
lx("tool.setAttr prim.makeVertex cenZ -$C11");
lx("tool.doApply");
lx("tool.setAttr prim.makeVertex cenX -$C1");
lx("tool.setAttr prim.makeVertex cenY $C2");
lx("tool.setAttr prim.makeVertex cenZ -$C14");
lx("tool.doApply");
lx("tool.setAttr prim.makeVertex cenX $C5");
lx("tool.setAttr prim.makeVertex cenY $C9");
lx("tool.setAttr prim.makeVertex cenZ -$C10");
lx("tool.doApply");
lx("tool.setAttr prim.makeVertex cenX $C4");
lx("tool.setAttr prim.makeVertex cenY $C3");
lx("tool.setAttr prim.makeVertex cenZ -$C13");
lx("tool.doApply");
lx("tool.setAttr prim.makeVertex cenX $C10");
lx("tool.setAttr prim.makeVertex cenY $C5");
lx("tool.setAttr prim.makeVertex cenZ -$C9");
lx("tool.doApply");
lx("tool.setAttr prim.makeVertex cenX -$C9");
lx("tool.setAttr prim.makeVertex cenY -$C10");
lx("tool.setAttr prim.makeVertex cenZ -$C5");
lx("tool.doApply");
lx("tool.setAttr prim.makeVertex cenX -$C13");
lx("tool.setAttr prim.makeVertex cenY -$C4");
lx("tool.setAttr prim.makeVertex cenZ -$C3");
lx("tool.doApply");
lx("tool.setAttr prim.makeVertex cenX -$C3");
lx("tool.setAttr prim.makeVertex cenY -$C13");
lx("tool.setAttr prim.makeVertex cenZ -$C4");
lx("tool.doApply");
lx("tool.setAttr prim.makeVertex cenX $C2");
lx("tool.setAttr prim.makeVertex cenY -$C14");
lx("tool.setAttr prim.makeVertex cenZ -$C1");
lx("tool.doApply");
lx("tool.setAttr prim.makeVertex cenX $C7");
lx("tool.setAttr prim.makeVertex cenY -$C11");
lx("tool.setAttr prim.makeVertex cenZ -$C6");
lx("tool.doApply");
lx("tool.setAttr prim.makeVertex cenX $C14");
lx("tool.setAttr prim.makeVertex cenY -$C1");
lx("tool.setAttr prim.makeVertex cenZ -$C2");
lx("tool.doApply");
lx("tool.setAttr prim.makeVertex cenX -$C12");
lx("tool.setAttr prim.makeVertex cenY $C8");
lx("tool.setAttr prim.makeVertex cenZ -$C0");
lx("tool.doApply");
lx("tool.setAttr prim.makeVertex cenX -$C7");
lx("tool.setAttr prim.makeVertex cenY $C11");
lx("tool.setAttr prim.makeVertex cenZ -$C6");
lx("tool.doApply");
lx("tool.setAttr prim.makeVertex cenX -$C14");
lx("tool.setAttr prim.makeVertex cenY $C1");
lx("tool.setAttr prim.makeVertex cenZ -$C2");
lx("tool.doApply");
lx("tool.setAttr prim.makeVertex cenX -$C2");
lx("tool.setAttr prim.makeVertex cenY $C14");
lx("tool.setAttr prim.makeVertex cenZ -$C1");
lx("tool.doApply");
lx("tool.setAttr prim.makeVertex cenX $C3");
lx("tool.setAttr prim.makeVertex cenY $C13");
lx("tool.setAttr prim.makeVertex cenZ -$C4");
lx("tool.doApply");
lx("tool.setAttr prim.makeVertex cenX $C9");
lx("tool.setAttr prim.makeVertex cenY $C10");
lx("tool.setAttr prim.makeVertex cenZ -$C5");
lx("tool.doApply");
lx("tool.setAttr prim.makeVertex cenX $C13");
lx("tool.setAttr prim.makeVertex cenY $C4");
lx("tool.setAttr prim.makeVertex cenZ -$C3");
lx("tool.doApply");
lx("tool.setAttr prim.makeVertex cenX -$C7");
lx("tool.setAttr prim.makeVertex cenY -$C11");
lx("tool.setAttr prim.makeVertex cenZ $C6");
lx("tool.doApply");
lx("tool.setAttr prim.makeVertex cenX -$C14");
lx("tool.setAttr prim.makeVertex cenY -$C1");
lx("tool.setAttr prim.makeVertex cenZ $C2");
lx("tool.doApply");
lx("tool.setAttr prim.makeVertex cenX -$C2");
lx("tool.setAttr prim.makeVertex cenY -$C14");
lx("tool.setAttr prim.makeVertex cenZ $C1");
lx("tool.doApply");
lx("tool.setAttr prim.makeVertex cenX $C3");
lx("tool.setAttr prim.makeVertex cenY -$C13");
lx("tool.setAttr prim.makeVertex cenZ $C4");
lx("tool.doApply");
lx("tool.setAttr prim.makeVertex cenX $C9");
lx("tool.setAttr prim.makeVertex cenY -$C10");
lx("tool.setAttr prim.makeVertex cenZ $C5");
lx("tool.doApply");
lx("tool.setAttr prim.makeVertex cenX $C13");
lx("tool.setAttr prim.makeVertex cenY -$C4");
lx("tool.setAttr prim.makeVertex cenZ $C3");
lx("tool.doApply");
lx("tool.setAttr prim.makeVertex cenX -$C9");
lx("tool.setAttr prim.makeVertex cenY $C10");
lx("tool.setAttr prim.makeVertex cenZ $C5");
lx("tool.doApply");
lx("tool.setAttr prim.makeVertex cenX -$C13");
lx("tool.setAttr prim.makeVertex cenY $C4");
lx("tool.setAttr prim.makeVertex cenZ $C3");
lx("tool.doApply");
lx("tool.setAttr prim.makeVertex cenX -$C3");
lx("tool.setAttr prim.makeVertex cenY $C13");
lx("tool.setAttr prim.makeVertex cenZ $C4");
lx("tool.doApply");
lx("tool.setAttr prim.makeVertex cenX $C2");
lx("tool.setAttr prim.makeVertex cenY $C14");
lx("tool.setAttr prim.makeVertex cenZ $C1");
lx("tool.doApply");
lx("tool.setAttr prim.makeVertex cenX $C12");
lx("tool.setAttr prim.makeVertex cenY $C8");
lx("tool.setAttr prim.makeVertex cenZ $C0");
lx("tool.doApply");
lx("tool.setAttr prim.makeVertex cenX $C7");
lx("tool.setAttr prim.makeVertex cenY $C11");
lx("tool.setAttr prim.makeVertex cenZ $C6");
lx("tool.doApply");
lx("tool.setAttr prim.makeVertex cenX $C14");
lx("tool.setAttr prim.makeVertex cenY $C1");
lx("tool.setAttr prim.makeVertex cenZ $C2");
lx("tool.doApply");
lx("tool.setAttr prim.makeVertex cenX -$C11");
lx("tool.setAttr prim.makeVertex cenY -$C6");
lx("tool.setAttr prim.makeVertex cenZ $C7");
lx("tool.doApply");
lx("tool.setAttr prim.makeVertex cenX -$C0");
lx("tool.setAttr prim.makeVertex cenY -$C12");
lx("tool.setAttr prim.makeVertex cenZ $C8");
lx("tool.doApply");
lx("tool.setAttr prim.makeVertex cenX -$C6");
lx("tool.setAttr prim.makeVertex cenY -$C7");
lx("tool.setAttr prim.makeVertex cenZ $C11");
lx("tool.doApply");
lx("tool.setAttr prim.makeVertex cenX -$C1");
lx("tool.setAttr prim.makeVertex cenY -$C2");
lx("tool.setAttr prim.makeVertex cenZ $C14");
lx("tool.doApply");
lx("tool.setAttr prim.makeVertex cenX $C5");
lx("tool.setAttr prim.makeVertex cenY -$C9");
lx("tool.setAttr prim.makeVertex cenZ $C10");
lx("tool.doApply");
lx("tool.setAttr prim.makeVertex cenX $C4");
lx("tool.setAttr prim.makeVertex cenY -$C3");
lx("tool.setAttr prim.makeVertex cenZ $C13");
lx("tool.doApply");
lx("tool.setAttr prim.makeVertex cenX $C10");
lx("tool.setAttr prim.makeVertex cenY -$C5");
lx("tool.setAttr prim.makeVertex cenZ $C9");
lx("tool.doApply");
lx("tool.setAttr prim.makeVertex cenX -$C10");
lx("tool.setAttr prim.makeVertex cenY $C5");
lx("tool.setAttr prim.makeVertex cenZ $C9");
lx("tool.doApply");
lx("tool.setAttr prim.makeVertex cenX -$C5");
lx("tool.setAttr prim.makeVertex cenY $C9");
lx("tool.setAttr prim.makeVertex cenZ $C10");
lx("tool.doApply");
lx("tool.setAttr prim.makeVertex cenX -$C4");
lx("tool.setAttr prim.makeVertex cenY $C3");
lx("tool.setAttr prim.makeVertex cenZ $C13");
lx("tool.doApply");
lx("tool.setAttr prim.makeVertex cenX $C6");
lx("tool.setAttr prim.makeVertex cenY $C7");
lx("tool.setAttr prim.makeVertex cenZ $C11");
lx("tool.doApply");
lx("tool.setAttr prim.makeVertex cenX $C1");
lx("tool.setAttr prim.makeVertex cenY $C2");
lx("tool.setAttr prim.makeVertex cenZ $C14");
lx("tool.doApply");
lx("tool.setAttr prim.makeVertex cenX $C11");
lx("tool.setAttr prim.makeVertex cenY $C6");
lx("tool.setAttr prim.makeVertex cenZ $C7");
lx("tool.doApply");
lx("tool.setAttr prim.makeVertex cenX $C8");
lx("tool.setAttr prim.makeVertex cenY $C0");
lx("tool.setAttr prim.makeVertex cenZ $C12");
lx("tool.doApply");
lx("tool.setAttr prim.makeVertex cenX $C0");
lx("tool.setAttr prim.makeVertex cenY -$C12");
lx("tool.setAttr prim.makeVertex cenZ -$C8");
lx("tool.doApply");
lx("tool.setAttr prim.makeVertex cenX $C12");
lx("tool.setAttr prim.makeVertex cenY -$C8");
lx("tool.setAttr prim.makeVertex cenZ -$C0");
lx("tool.doApply");
lx("tool.setAttr prim.makeVertex cenX -$C8");
lx("tool.setAttr prim.makeVertex cenY $C0");
lx("tool.setAttr prim.makeVertex cenZ -$C12");
lx("tool.doApply");
lx("tool.setAttr prim.makeVertex cenX -$C12");
lx("tool.setAttr prim.makeVertex cenY -$C8");
lx("tool.setAttr prim.makeVertex cenZ $C0");
lx("tool.doApply");
lx("tool.setAttr prim.makeVertex cenX -$C8");
lx("tool.setAttr prim.makeVertex cenY -$C0");
lx("tool.setAttr prim.makeVertex cenZ $C12");
lx("tool.doApply");
lx("tool.setAttr prim.makeVertex cenX $C0");
lx("tool.setAttr prim.makeVertex cenY $C12");
lx("tool.setAttr prim.makeVertex cenZ $C8");
lx("tool.doApply");
lx("tool.set prim.makeVertex off 0");
lx("select.drop vertex");
lx("select.element $layerindex vertex add 33");
lx("select.element $layerindex vertex add 20");
lx("select.element $layerindex vertex add 34");
lx("poly.make face");
lx("select.element $layerindex vertex add 35");
lx("select.element $layerindex vertex add 33");
lx("select.element $layerindex vertex add 48");
lx("poly.make face");
lx("select.element $layerindex vertex add 23");
lx("select.element $layerindex vertex add 35");
lx("select.element $layerindex vertex add 36");
lx("poly.make face");
lx("select.element $layerindex vertex add 21");
lx("select.element $layerindex vertex add 23");
lx("select.element $layerindex vertex add 8");
lx("poly.make face");
lx("select.element $layerindex vertex add 20");
lx("select.element $layerindex vertex add 21");
lx("select.element $layerindex vertex add 7");
lx("poly.make face");
lx("select.element $layerindex vertex add 25");
lx("select.element $layerindex vertex add 37");
lx("select.element $layerindex vertex add 26");
lx("poly.make face");
lx("select.element $layerindex vertex add 24");
lx("select.element $layerindex vertex add 25");
lx("select.element $layerindex vertex add 11");
lx("poly.make face");
lx("select.element $layerindex vertex add 36");
lx("select.element $layerindex vertex add 24");
lx("select.element $layerindex vertex add 23");
lx("poly.make face");
lx("select.element $layerindex vertex add 37");
lx("select.element $layerindex vertex add 38");
lx("select.element $layerindex vertex add 52");
lx("poly.make face");
lx("select.element $layerindex vertex add 30");
lx("select.element $layerindex vertex add 31");
lx("select.element $layerindex vertex add 44");
lx("poly.make face");
lx("select.element $layerindex vertex add 17");
lx("select.element $layerindex vertex add 30");
lx("select.element $layerindex vertex add 29");
lx("poly.make face");
lx("select.element $layerindex vertex add 16");
lx("select.element $layerindex vertex add 14");
lx("select.element $layerindex vertex add 1");
lx("poly.make face");
lx("select.element $layerindex vertex add 29");
lx("select.element $layerindex vertex add 16");
lx("select.element $layerindex vertex add 17");
lx("poly.make face");
lx("select.element $layerindex vertex add 27");
lx("select.element $layerindex vertex add 29");
lx("select.element $layerindex vertex add 41");
lx("poly.make face");
lx("select.element $layerindex vertex add 46");
lx("select.element $layerindex vertex add 53");
lx("select.element $layerindex vertex add 45");
lx("poly.make face");
lx("select.element $layerindex vertex add 32");
lx("select.element $layerindex vertex add 46");
lx("select.element $layerindex vertex add 31");
lx("poly.make face");
lx("select.element $layerindex vertex add 39");
lx("select.element $layerindex vertex add 32");
lx("select.element $layerindex vertex add 19");
lx("poly.make face");
lx("select.element $layerindex vertex add 52");
lx("select.element $layerindex vertex add 39");
lx("select.element $layerindex vertex add 37");
lx("poly.make face");
lx("select.element $layerindex vertex add 53");
lx("select.element $layerindex vertex add 52");
lx("select.element $layerindex vertex add 50");
lx("poly.make face");
lx("select.element $layerindex vertex add 13");
lx("select.element $layerindex vertex add 6");
lx("select.element $layerindex vertex add 12");
lx("poly.make face");
lx("select.element $layerindex vertex add 26");
lx("select.element $layerindex vertex add 13");
lx("select.element $layerindex vertex add 25");
lx("poly.make face");
lx("select.element $layerindex vertex add 19");
lx("select.element $layerindex vertex add 26");
lx("select.element $layerindex vertex add 39");
lx("poly.make face");
lx("select.element $layerindex vertex add 6");
lx("select.element $layerindex vertex add 5");
lx("select.element $layerindex vertex add 3");
lx("poly.make face");
lx("select.element $layerindex vertex add 15");
lx("select.element $layerindex vertex add 0");
lx("select.element $layerindex vertex add 14");
lx("poly.make face");
lx("select.element $layerindex vertex add 22");
lx("select.element $layerindex vertex add 15");
lx("select.element $layerindex vertex add 28");
lx("poly.make face");
lx("select.element $layerindex vertex add 7");
lx("select.element $layerindex vertex add 22");
lx("select.element $layerindex vertex add 20");
lx("poly.make face");
lx("select.element $layerindex vertex add 34");
lx("select.element $layerindex vertex add 47");
lx("select.element $layerindex vertex add 33");
lx("poly.make face");
lx("select.element $layerindex vertex add 28");
lx("select.element $layerindex vertex add 34");
lx("select.element $layerindex vertex add 22");
lx("poly.make face");
lx("select.element $layerindex vertex add 44");
lx("select.element $layerindex vertex add 41");
lx("select.element $layerindex vertex add 30");
lx("poly.make face");
lx("select.element $layerindex vertex add 45");
lx("select.element $layerindex vertex add 44");
lx("select.element $layerindex vertex add 46");
lx("poly.make face");
lx("select.element $layerindex vertex add 43");
lx("select.element $layerindex vertex add 45");
lx("select.element $layerindex vertex add 51");
lx("poly.make face");
lx("select.element $layerindex vertex add 41");
lx("select.element $layerindex vertex add 42");
lx("select.element $layerindex vertex add 27");
lx("poly.make face");
lx("select.element $layerindex vertex add 49");
lx("select.element $layerindex vertex add 48");
lx("select.element $layerindex vertex add 47");
lx("poly.make face");
lx("select.element $layerindex vertex add 51");
lx("select.element $layerindex vertex add 49");
lx("select.element $layerindex vertex add 43");
lx("poly.make face");
lx("select.element $layerindex vertex add 50");
lx("select.element $layerindex vertex add 51");
lx("select.element $layerindex vertex add 53");
lx("poly.make face");
lx("select.element $layerindex vertex add 11");
lx("select.element $layerindex vertex add 8");
lx("select.element $layerindex vertex add 24");
lx("poly.make face");
lx("select.element $layerindex vertex add 12");
lx("select.element $layerindex vertex add 11");
lx("select.element $layerindex vertex add 13");
lx("poly.make face");
lx("select.element $layerindex vertex add 10");
lx("select.element $layerindex vertex add 12");
lx("select.element $layerindex vertex add 4");
lx("poly.make face");
lx("select.element $layerindex vertex add 8");
lx("select.element $layerindex vertex add 9");
lx("select.element $layerindex vertex add 21");
lx("poly.make face");
lx("select.element $layerindex vertex add 2");
lx("select.element $layerindex vertex add 1");
lx("select.element $layerindex vertex add 0");
lx("poly.make face");
lx("select.element $layerindex vertex add 4");
lx("select.element $layerindex vertex add 2");
lx("select.element $layerindex vertex add 10");
lx("poly.make face");
lx("select.element $layerindex vertex add 3");
lx("select.element $layerindex vertex add 4");
lx("select.element $layerindex vertex add 6");
lx("poly.make face");
lx("select.element $layerindex vertex add 38");
lx("select.element $layerindex vertex add 36");
lx("select.element $layerindex vertex add 59");
lx("poly.make face");
lx("select.element $layerindex vertex add 31");
lx("select.element $layerindex vertex add 55");
lx("select.element $layerindex vertex add 32");
lx("poly.make face");
lx("select.element $layerindex vertex add 18");
lx("select.element $layerindex vertex add 17");
lx("select.element $layerindex vertex add 54");
lx("poly.make face");
lx("select.element $layerindex vertex add 55");
lx("select.element $layerindex vertex add 18");
lx("select.element $layerindex vertex add 5");
lx("poly.make face");
lx("select.element $layerindex vertex add 14");
lx("select.element $layerindex vertex add 57");
lx("select.element $layerindex vertex add 15");
lx("poly.make face");
lx("select.element $layerindex vertex add 57");
lx("select.element $layerindex vertex add 27");
lx("select.element $layerindex vertex add 40");
lx("poly.make face");
lx("select.element $layerindex vertex add 5");
lx("select.element $layerindex vertex add 19");
lx("select.element $layerindex vertex add 55");
lx("poly.make face");
lx("select.element $layerindex vertex add 0");
lx("select.element $layerindex vertex add 56");
lx("select.element $layerindex vertex add 2");
lx("poly.make face");
lx("select.element $layerindex vertex add 56");
lx("select.element $layerindex vertex add 7");
lx("select.element $layerindex vertex add 9");
lx("poly.make face");
lx("select.element $layerindex vertex add 47");
lx("select.element $layerindex vertex add 58");
lx("select.element $layerindex vertex add 49");
lx("poly.make face");
lx("select.element $layerindex vertex add 40");
lx("select.element $layerindex vertex add 28");
lx("select.element $layerindex vertex add 57");
lx("poly.make face");
lx("select.element $layerindex vertex add 58");
lx("select.element $layerindex vertex add 40");
lx("select.element $layerindex vertex add 42");
lx("poly.make face");
lx("select.element $layerindex vertex add 42");
lx("select.element $layerindex vertex add 43");
lx("select.element $layerindex vertex add 58");
lx("poly.make face");
lx("select.element $layerindex vertex add 48");
lx("select.element $layerindex vertex add 59");
lx("select.element $layerindex vertex add 35");
lx("poly.make face");
lx("select.element $layerindex vertex add 59");
lx("select.element $layerindex vertex add 50");
lx("select.element $layerindex vertex add 38");
lx("poly.make face");
lx("select.element $layerindex vertex add 9");
lx("select.element $layerindex vertex add 10");
lx("select.element $layerindex vertex add 56");
lx("poly.make face");
lx("select.element $layerindex vertex add 1");
lx("select.element $layerindex vertex add 54");
lx("select.element $layerindex vertex add 16");
lx("poly.make face");
lx("select.element $layerindex vertex add 54");
lx("select.element $layerindex vertex add 3");
lx("select.element $layerindex vertex add 18");
lx("poly.make face");
lx("select.element $layerindex vertex add 12");
lx("select.element $layerindex vertex add 6");
lx("select.element $layerindex vertex add 4");
lx("poly.make face");
lx("select.element $layerindex vertex add 0");
lx("select.element $layerindex vertex add 1");
lx("select.element $layerindex vertex add 14");
lx("poly.make face");
lx("select.element $layerindex vertex add 44");
lx("select.element $layerindex vertex add 31");
lx("select.element $layerindex vertex add 46");
lx("poly.make face");
lx("select.element $layerindex vertex add 13");
lx("select.element $layerindex vertex add 11");
lx("select.element $layerindex vertex add 25");
lx("poly.make face");
lx("select.element $layerindex vertex add 59");
lx("select.element $layerindex vertex add 36");
lx("select.element $layerindex vertex add 35");
lx("poly.make face");
lx("select.element $layerindex vertex add 48");
lx("select.element $layerindex vertex add 33");
lx("select.element $layerindex vertex add 47");
lx("poly.make face");
lx("select.element $layerindex vertex add 51");
lx("select.element $layerindex vertex add 45");
lx("select.element $layerindex vertex add 53");
lx("poly.make face");
lx("select.element $layerindex vertex add 41");
lx("select.element $layerindex vertex add 29");
lx("select.element $layerindex vertex add 30");
lx("poly.make face");
lx("select.element $layerindex vertex add 49");
lx("select.element $layerindex vertex add 58");
lx("select.element $layerindex vertex add 43");
lx("poly.make face");
lx("select.element $layerindex vertex add 16");
lx("select.element $layerindex vertex add 54");
lx("select.element $layerindex vertex add 17");
lx("poly.make face");
lx("select.element $layerindex vertex add 10");
lx("select.element $layerindex vertex add 2");
lx("select.element $layerindex vertex add 56");
lx("poly.make face");
lx("select.element $layerindex vertex add 37");
lx("select.element $layerindex vertex add 39");
lx("select.element $layerindex vertex add 26");
lx("poly.make face");
lx("select.element $layerindex vertex add 52");
lx("select.element $layerindex vertex add 38");
lx("select.element $layerindex vertex add 50");
lx("poly.make face");
lx("select.element $layerindex vertex add 15");
lx("select.element $layerindex vertex add 57");
lx("select.element $layerindex vertex add 28");
lx("poly.make face");
lx("select.element $layerindex vertex add 3");
lx("select.element $layerindex vertex add 5");
lx("select.element $layerindex vertex add 18");
lx("poly.make face");
lx("select.element $layerindex vertex add 19");
lx("select.element $layerindex vertex add 32");
lx("select.element $layerindex vertex add 55");
lx("poly.make face");
lx("select.element $layerindex vertex add 21");
lx("select.element $layerindex vertex add 9");
lx("select.element $layerindex vertex add 7");
lx("poly.make face");
lx("select.element $layerindex vertex add 20");
lx("select.element $layerindex vertex add 22");
lx("select.element $layerindex vertex add 34");
lx("poly.make face");
lx("select.element $layerindex vertex add 8");
lx("select.element $layerindex vertex add 23");
lx("select.element $layerindex vertex add 24");
lx("poly.make face");
lx("select.element $layerindex vertex add 40");
lx("select.element $layerindex vertex add 27");
lx("select.element $layerindex vertex add 42");
lx("poly.make face");
lx("select.element $layerindex vertex add 20");
lx("select.element $layerindex vertex add 33");
lx("select.element $layerindex vertex add 35");
lx("select.element $layerindex vertex add 23");
lx("select.element $layerindex vertex add 21");
lx("poly.make face");
lx("select.element $layerindex vertex add 38");
lx("select.element $layerindex vertex add 37");
lx("select.element $layerindex vertex add 25");
lx("select.element $layerindex vertex add 24");
lx("select.element $layerindex vertex add 36");
lx("poly.make face");
lx("select.element $layerindex vertex add 31");
lx("select.element $layerindex vertex add 30");
lx("select.element $layerindex vertex add 17");
lx("select.element $layerindex vertex add 18");
lx("select.element $layerindex vertex add 55");
lx("poly.make face");
lx("select.element $layerindex vertex add 14");
lx("select.element $layerindex vertex add 16");
lx("select.element $layerindex vertex add 29");
lx("select.element $layerindex vertex add 27");
lx("select.element $layerindex vertex add 57");
lx("poly.make face");
lx("select.element $layerindex vertex add 53");
lx("select.element $layerindex vertex add 46");
lx("select.element $layerindex vertex add 32");
lx("select.element $layerindex vertex add 39");
lx("select.element $layerindex vertex add 52");
lx("poly.make face");
lx("select.element $layerindex vertex add 6");
lx("select.element $layerindex vertex add 13");
lx("select.element $layerindex vertex add 26");
lx("select.element $layerindex vertex add 19");
lx("select.element $layerindex vertex add 5");
lx("poly.make face");
lx("select.element $layerindex vertex add 56");
lx("select.element $layerindex vertex add 0");
lx("select.element $layerindex vertex add 15");
lx("select.element $layerindex vertex add 22");
lx("select.element $layerindex vertex add 7");
lx("poly.make face");
lx("select.element $layerindex vertex add 58");
lx("select.element $layerindex vertex add 47");
lx("select.element $layerindex vertex add 34");
lx("select.element $layerindex vertex add 28");
lx("select.element $layerindex vertex add 40");
lx("poly.make face");
lx("select.element $layerindex vertex add 45");
lx("select.element $layerindex vertex add 43");
lx("select.element $layerindex vertex add 42");
lx("select.element $layerindex vertex add 41");
lx("select.element $layerindex vertex add 44");
lx("poly.make face");
lx("select.element $layerindex vertex add 51");
lx("select.element $layerindex vertex add 50");
lx("select.element $layerindex vertex add 59");
lx("select.element $layerindex vertex add 48");
lx("select.element $layerindex vertex add 49");
lx("poly.make face");
lx("select.element $layerindex vertex add 12");
lx("select.element $layerindex vertex add 10");
lx("select.element $layerindex vertex add 9");
lx("select.element $layerindex vertex add 8");
lx("select.element $layerindex vertex add 11");
lx("poly.make face");
lx("select.element $layerindex vertex add 4");
lx("select.element $layerindex vertex add 3");
lx("select.element $layerindex vertex add 54");
lx("select.element $layerindex vertex add 1");
lx("select.element $layerindex vertex add 2");
lx("poly.make face");
lx("tool.set uv.create on");
lx("tool.attr uv.create proj barycentric");
lx("tool.setAttr uv.create cenX 0.0");
lx("tool.setAttr uv.create cenY 0.0");
lx("tool.setAttr uv.create cenZ 0.0");
lx("tool.setAttr uv.create sizX [5^.5*.5+.5]");
lx("tool.setAttr uv.create sizY [5^.5*.5+.5]");
lx("tool.setAttr uv.create sizZ [5^.5*.5+.5]");
lx("tool.setAttr uv.create seam 0.0");
lx("tool.setAttr uv.create axis 2");
lx("tool.doApply");
lx("tool.set uv.create off 0");
lx("uv.pack true false false auto 0.2 false");
lx("select.type edge");
lx("select.element $layerindex edge set 57 14 83");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 14 16 83");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 16 29 83");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 29 27 83");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 27 57 83");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 47 34 87");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 34 28 87");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 28 40 87");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 40 58 87");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 15 22 86");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 22 7 86");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 7 56 86");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 56 0 86");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 0 15 86");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 54 1 91");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 1 2 91");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 2 4 91");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 4 3 91");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 3 54 91");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 31 30 82");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 30 17 82");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 17 18 82");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 18 55 82");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 55 31 82");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 44 45 88");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 45 43 88");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 43 42 88");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 42 41 88");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 41 44 88");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 36 38 81");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 38 37 81");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 37 25 81");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 25 24 81");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 24 36 81");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 6 13 85");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 13 26 85");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 26 19 85");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 19 5 85");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 5 6 85");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 12 10 90");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 10 9 90");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 9 8 90");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 8 11 90");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 11 12 90");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 21 20 80");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 20 33 80");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 33 35 80");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 35 23 80");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 23 21 80");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 48 49 89");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 49 51 89");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 51 50 89");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 50 59 89");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 59 48 89");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 53 46 84");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 46 32 84");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 32 39 84");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 39 52 84");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 52 53 84");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 15 14 46");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 1 16 11");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 14 1 11");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 17 29 12");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 16 17 12");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 41 27 13");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 29 41 13");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 40 57 47");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 27 40 47");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 52 37 8");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 38 52 8");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 26 25 5");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 37 26 5");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 11 24 6");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 25 11 6");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 23 36 7");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 24 23 7");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 59 38 42");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 36 59 42");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 53 45 14");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 32 19 16");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 47 33 26");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 44 46 29");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 47 49 32");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 48 47 32");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 49 43 33");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 12 4 37");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 18 5 45");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 56 2 49");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 7 9 50");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 57 15 46");
lx("uv.sewMove select 1");
lx("select.element $layerindex edge set 34 22 77");
lx("uv.sewMove select 1");
lx("uv.fit false");
lx("select.drop polygon");
lx("tool.set actr.auto on");
lx("tool.set TransformScale on");
lx("tool.reset");
lx("tool.viewType uv");
lx("tool.setAttr xfrm.transform SX .99");
lx("tool.setAttr xfrm.transform SY .99");
lx("tool.doApply");
lx("tool.set TransformScale off");
lx("tool.set TransformMove on");
lx("tool.reset");
lx("tool.viewType uv");
lx("tool.setAttr xfrm.transform U .005");
lx("tool.setAttr xfrm.transform V .005");
lx("tool.doApply");
lx("tool.viewType xyz");
lx("tool.set TransformMove off");
lx("tool.set actr.auto off");
lx("select.drop vertex");

lx("pref.value units.system $units");